---
title: "Linguistic examples and semi-automatic creation of abbreviation list with `lingglosses` package"
author: "G. Moroz, [NRU HSE Linguistic Convergence Laboratory](https://ilcl.hse.ru/en/)"
date: "`r Sys.Date()`"
bibliography: bibliography.bib
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Linguistic examples and semi-automatic creation of abbreviation list with `lingglosses` package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

Abbreviation list is obligatory part of linguistic articles that nobody reads. This lists contains definitions of abbreviations used in the article (e. g. corpora names or sign language names), but also a list of linguistic glosses --- abbreviations used in linguistic interlinear examples. There is a standardized list of glossing rules [@comrie08] which ends with a list of 84 standard abbreviations. However researchers can deviate from this list and provide their own abbreviations.

The worst abbreviation list that I have found in a published article make it clear that there is a room for improvement:

```
NOM = nominative, GEN = nominative, DAT = nominative, ACC = accusative, VOC = accusative, LOC = accusative, INS = accusative, PL = plural, SG = singular
```

Except obvious mistakes in this list there are some more problems that I wanted to emphasize:

* lack of the alphabetic order;
* there is also some abbreviation (SBJV, IMP) in the article that are absent in the abbreviation list.

The main goal of `lingglosses` package is to provide an option for creating:

* linguistic glosses for html output of rmarkdown;
* semi-automatic compiled abbreviation list.

# References
